project:
  type: book
  output-dir: docs



book:
  title: "libro"
  author: "Javier E"
  date: "15/03/2023"
  site-url: https://javierkiller.github.io/ejercicioLibro/
  repo-url: https://github.com/JavierKiller/ejercicioLibro.git
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Introduction to R"
      chapters:
        - Introduction_to_R_C1.qmd
        - Introduction_to_R_C2.qmd
        - Introduction_to_R_C3.qmd
        - Introduction_to_R_C4.qmd
        - Introduction_to_R_C5.qmd
    - part: "Intermedio R"
      chapters:
      
        - Intermedio_R_C1.qmd
        - Intermedio_R_C2.qmd
        - Intermedio_R_C3.qmd
        - Intermedio_R_C4.qmd    
        - Intermedio_R_C5.qmd
    - part: "Introduction to Writing Functions in R"
      chapters:
        - Introduction_to_Writing_Functions_in_R_C1.qmd    
        - Introduction_to_Writing_Functions_in_R_C3.qmd   
        - Introduction_to_Writing_Functions_in_R_C3.qmd   
        - Introduction_to_Writing_Functions_in_R_C4.qmd       
    - part: "Introduction to Importing Data in R"
      chapters:
        - Introduction_to_Importing_Data_in_R_C1.qmd 
        - Introduction_to_Importing_Data_in_R_C2.qmd 
        - Introduction_to_Importing_Data_in_R_C3.qmd 
        - Introduction_to_Importing_Data_in_R_C4.qmd       
    - part: "Data Manipulation with dplyr"
      chapters:
        - Data_Manipulation_with_dplyr_C1.qmd 
        - Data_Manipulation_with_dplyr_C2.qmd 
        - Data_Manipulation_with_dplyr_C3.qmd 
        - Data_Manipulation_with_dplyr_C4.qmd       
    - part: "Cleaning Data in R"
      chapters:
        - Cleaning_Data_in_R_C1.qmd 
        - Cleaning_Data_in_R_C2.qmd 
        - Cleaning_Data_in_R_C3.qmd 
        - Cleaning_Data_in_R_C4.qmd       
    - part: "Reshaping Data with tidyr"
      chapters:
        - Reshaping_Data_with_tidyr_C1.qmd 
        - Reshaping_Data_with_tidyr_C2.qmd 
        - Reshaping_Data_with_tidyr_C3.qmd 
        - Reshaping_Data_with_tidyr_C4.qmd   

bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt

editor: visual

# lux darkly cyborg vapor sketchy slate

