project:
  type: book
  output-dir: docs



book:
  title: "libro"
  author: "Javier E"
  date: "15/03/2023"
  site-url: https://javierkiller.github.io/ejercicioLibro/
  repo-url: https://github.com/JavierKiller/ejercicioLibro.git
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Introduction to R"
      chapters:
        - Introduction_to_R_C1.qmd
        - Introduction_to_R_C2.qmd
        - Introduction_to_R_C3.qmd
        - Introduction_to_R_C4.qmd
        - Introduction_to_R_C5.qmd
    - part: "Intermedio R"
      chapters:
      
        - Intermedio_R_C1.qmd
        - Intermedio_R_C2.qmd
        - Intermedio_R_C3.qmd
        - Intermedio_R_C4.qmd    
        - Intermedio_R_C5.qmd
    - part: "Introduction to Writing Functions in R"
      chapters:
        - Introduction_to_Writing_Functions_in_R_C1.qmd    
        - Introduction_to_Writing_Functions_in_R_C2.qmd   
        - Introduction_to_Writing_Functions_in_R_C3.qmd   
        - Introduction_to_Writing_Functions_in_R_C4.qmd       
    - part: "Introduction to Importing Data in R"
      chapters:
        - Introduction_to_Importing_Data_in_R_C1.qmd 
        - Introduction_to_Importing_Data_in_R_C2.qmd 
        - Introduction_to_Importing_Data_in_R_C3.qmd 
        - Introduction_to_Importing_Data_in_R_C4.qmd       
    - part: "Data Manipulation with dplyr"
      chapters:
        - Data_Manipulation_with_dplyr_C1.qmd 
        - Data_Manipulation_with_dplyr_C2.qmd 
        - Data_Manipulation_with_dplyr_C3.qmd 
        - Data_Manipulation_with_dplyr_C4.qmd       
    - part: "Cleaning Data in R"
      chapters:
        - Cleaning_Data_in_R_C1.qmd 
        - Cleaning_Data_in_R_C2.qmd 
        - Cleaning_Data_in_R_C3.qmd 
        - Cleaning_Data_in_R_C4.qmd       
    - part: "Reshaping Data with tidyr"
      chapters:
        - Reshaping_Data_with_tidyr_C1.qmd 
        - Reshaping_Data_with_tidyr_C2.qmd 
        - Reshaping_Data_with_tidyr_C3.qmd 
        - Reshaping_Data_with_tidyr_C4.qmd   
    - part: "Dealing With Missing Data in R"
      chapters:
        - Dealing_With_Missing_Data_in_R_C1.qmd 
        - Dealing_With_Missing_Data_in_R_C2.qmd 
        - Dealing_With_Missing_Data_in_R_C3.qmd 
        - Dealing_With_Missing_Data_in_R_C4.qmd  
    - part: "Developing R Packages"
      chapters:
        - Developing_R_Packages_C1.qmd 
        - Developing_R_Packages_C2.qmd 
        - Developing_R_Packages_C3.qmd 
        - Developing_R_Packages_C4.qmd  
    - part: "Introduction to Statistics in R"
      chapters:
        - Introduction_to_Statistics_in_R_C1.qmd 
        - Introduction_to_Statistics_in_R_C2.qmd 
        - Introduction_to_Statistics_in_R_C3.qmd 
        - Introduction_to_Statistics_in_R_C4.qmd  
    - part: "Introduction to Regression in R"
      chapters:
        - Introduction_to_Regression_in_R_C1.qmd 
        - Introduction_to_Regression_in_R_C2.qmd 
        - Introduction_to_Regression_in_R_C3.qmd 
        - Introduction_to_Regression_in_R_C4.qmd  
    - part: "Intermediate Regression in R"
      chapters:
        - Intermediate_Regression_in_R_C1.qmd 
        - Intermediate_Regression_in_R_C2.qmd 
        - Intermediate_Regression_in_R_C3.qmd 
        - Intermediate_Regression_in_R_C4.qmd  
    - part: "Sampling in R"
      chapters:
        - Sampling_in_R_C1.qmd 
        - Sampling_in_R_C2.qmd 
        - Sampling_in_R_C3.qmd 
        - Sampling_in_R_C4.qmd  
    - part: "Hypothesis Testing in R"
      chapters:
        - Hypothesis_Testing_in_R_C1.qmd 
        - Hypothesis_Testing_in_R_C2.qmd 
        - Hypothesis_Testing_in_R_C3.qmd 
        - Hypothesis_Testing_in_R_C4.qmd  


bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt

editor: visual


#Statistics Fundamentals with R
#Spatial Data with R
# lux darkly cyborg vapor sketchy slate  

